### ISSUE TITLE
Add Debug Module support?

### ISSUE THREAD

**Issue by sheldon-cooper0** [sycuricon/starship#2]

**Comment by Phantom1003** [comment]
Can you elaborate on your requirements, e.g. what do you want to debug? As starship is only for evaluation on the FPGA, we will assume that all the software has been verified on the simulator.

**Comment by sheldon-cooper0** [comment]
I was thinking about porting starship to other board since I don't have VC707.

My FPGA board doesn't have DDR or TF card support, so i tend to use scratchpad as main memory (which cant be large), and JTAG DTM to load custom program.

But i found "case DebugModuleKey => None", which means there's no DM support on starship.

**Comment by Phantom1003** [comment]
starship now supports JTAG #9
