### ISSUE TITLE
Verilator Version

### ISSUE THREAD

**Issue by pointerliu** [sycuricon/starship#20]
Hi, I met some issues when executing `make vlt`.
Which version of verilator should I use ?

**Comment by Phantom1003** [comment]
We typically use the latest version of Verilator from the community upstream (v5.024+).

**Comment by pointerliu** [comment]
Thanks for you reply.
I'm using the latest version but still met the following issue:
```bash
%Error: /xxx/starship/asic/sim/spike_difftest.rocket.v:2:27: Can't find definition of 'ldut' in dotted scope/variable: 'Testbench.testHarness.ldut'
```
Did I miss some steps ?

**Comment by Phantom1003** [comment]
It appears that you are attempting to simulate an FPGA configuration, which includes several Xilinx IPs. As we do not yet support Verilator on this configuration, you can modify the variables in the `conf/build.mk` as shown below to generate RTL with a simulation configuration:

```
STARSHIP_TH 	?= starship.asic.TestHarness
STARSHIP_TOP	?= starship.asic.StarshipSimTop
STARSHIP_CONFIG	?= starship.asic.StarshipSimConfig
```
